version: "3.9"
services:
  blink-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/blink-debug:${TAG}
    ports:
      - 2222:2222
    devices:
      - /dev/gpiochip0

  blink:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/blink:${TAG}
    devices:
      - /dev/gpiochip0
